workflows:
  android-build:
    name: Build Debug APK
    max_build_duration: 15
    environment:
      vars:
        JAVA_HOME: /opt/android-studio/jre
    scripts:
      - echo "📦 Starting APK Build..."
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
