workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.tracknsave.app"
      android_signing:
        - keystore_reference
      flutter: stable
    scripts:
      - echo "Starting APK Build"
      - chmod +x gradlew
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
