workflows:
  android-build:
    name: TrackNSave APK Build
    max_build_duration: 15
    scripts:
      - echo "📦 Starting APK Build..."
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - keerthyvasaan@gmail.com
