workflows:
  android-build:
    name: Build Debug APK
    max_build_duration: 15
    environment:
      android:
        sdk: 34
    scripts:
      - echo "📦 Building Debug APK..."
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
